package org.chimera.koronos;

import org.chimera.cognition.Vector128D;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/** H2-backed embedded kernel database. The database is created below the supplied data directory. */
public final class H2KernelDataStore implements KernelDataStore {
    public static final String DATABASE_FILE = "kernel";
    private final Connection connection;

    public H2KernelDataStore(Path dataDirectory) {
        try {
            Files.createDirectories(dataDirectory);
            Path database = dataDirectory.resolve(DATABASE_FILE).toAbsolutePath();
            connection = DriverManager.getConnection("jdbc:h2:file:" + database + ";AUTO_SERVER=FALSE", "sa", "");
            initialize();
        } catch (IOException | SQLException e) {
            throw new IllegalStateException("Unable to initialize Chimera kernel database", e);
        }
    }

    private void initialize() throws SQLException {
        try (Statement s = connection.createStatement()) {
            s.executeUpdate("CREATE TABLE IF NOT EXISTS observations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP WITH TIME ZONE NOT NULL, vector VARCHAR(4096) NOT NULL)");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS learning_events (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP WITH TIME ZONE NOT NULL, loss DOUBLE NOT NULL)");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS model_snapshots (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created_at TIMESTAMP WITH TIME ZONE NOT NULL, model BLOB NOT NULL)");
        }
    }

    @Override public synchronized void recordObservation(Vector128D observation) {
        try (var p = connection.prepareStatement("INSERT INTO observations(created_at, vector) VALUES (CURRENT_TIMESTAMP, ?)");) {
            p.setString(1, encode(observation));
            p.executeUpdate();
        } catch (SQLException e) { throw failure(e); }
    }

    @Override public synchronized void recordLearning(double loss) {
        try (var p = connection.prepareStatement("INSERT INTO learning_events(created_at, loss) VALUES (CURRENT_TIMESTAMP, ?)");) {
            p.setDouble(1, loss);
            p.executeUpdate();
        } catch (SQLException e) { throw failure(e); }
    }

    @Override public synchronized void saveModel(byte[] modelState) {
        try (var p = connection.prepareStatement("INSERT INTO model_snapshots(created_at, model) VALUES (CURRENT_TIMESTAMP, ?)");) {
            p.setBytes(1, modelState.clone());
            p.executeUpdate();
        } catch (SQLException e) { throw failure(e); }
    }

    @Override public synchronized long observationCount() { return count("observations"); }
    @Override public synchronized long learningCount() { return count("learning_events"); }
    @Override public synchronized long snapshotCount() { return count("model_snapshots"); }

    @Override public synchronized Double lastLearningLoss() {
        try (var p = connection.prepareStatement("SELECT loss FROM learning_events ORDER BY id DESC LIMIT 1"); ResultSet r = p.executeQuery()) {
            return r.next() ? r.getDouble(1) : null;
        } catch (SQLException e) { throw failure(e); }
    }

    @Override public synchronized byte[] latestModel() {
        try (var p = connection.prepareStatement("SELECT model FROM model_snapshots ORDER BY id DESC LIMIT 1"); ResultSet r = p.executeQuery()) {
            return r.next() ? r.getBytes(1) : null;
        } catch (SQLException e) { throw failure(e); }
    }

    private long count(String table) {
        try (var p = connection.prepareStatement("SELECT COUNT(*) FROM " + table); ResultSet r = p.executeQuery()) {
            r.next();
            return r.getLong(1);
        } catch (SQLException e) { throw failure(e); }
    }

    private static String encode(Vector128D vector) {
        var b = new StringBuilder();
        for (int i = 0; i < Vector128D.DIM; i++) {
            if (i != 0) b.append(',');
            b.append(Double.toString(vector.get(i)));
        }
        return b.toString();
    }

    private static IllegalStateException failure(SQLException e) { return new IllegalStateException("Kernel database operation failed", e); }

    @Override public synchronized void close() {
        try { connection.close(); } catch (SQLException e) { throw failure(e); }
    }
}
